sprint_11
BezrukovAndrej/ImageFeed pull request #4
Opened 2023-05-13 16:10 UTC by BezrukovAndrej

2023-05-14 14:56 UTC, mmbabaev requested changes

2023-05-14 14:56 UTC, mmbabaev commented on ImageFeed/Services/ProfileServices/ProfileImageService.swift
> +final class ProfileImageServices {
почему множественное число?

2023-05-14 14:56 UTC, mmbabaev commented on ImageFeed/Services/ProfileServices/ProfileService.swift
> +                completion(.success(profile))
лучше вызывать completion именно в конце. Вызывающий код может ожидать, что profile уже проставлен

2023-05-14 14:56 UTC, mmbabaev commented on ImageFeed/ViewControllers/TabBarController/TabBarController.swift
> +        self.viewControllers?.enumerated().forEach {
этот код можно сделать внутри кожуры map, тогда код будет чище и не нужен будет enumerated

2023-06-09 10:54 UTC, BezrukovAndrej commented
sprint_11 #5

2023-06-09 10:54 UTC, BezrukovAndrej commented
sprint_11 https://github.com/BezrukovAndrej/ImageFeed/pull/5

2023-06-09 10:55 UTC, closed without merging